services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5832:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stackhub
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native TCP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: securepassword
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8123/ping | grep -q 'Ok'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  clickhouse_data:
