import { listTech } from '@specfy/stack-analyser/dist/common/techs.generated';

import type { AllowedKeys, TechItem } from '@specfy/stack-analyser';

export type TechItemExtended = { website: string } & TechItem;

// Hardcode the website URL for each entry
const extendedInfo: Record<AllowedKeys, { website?: string; github?: string; iconURL?: string }> = {
  adminer: { website: 'https://www.adminer.org/' },
  adobe: { website: 'https://www.adobe.com/' },
  adobecommercecloud: {
    website: 'https://business.adobe.com/products/commerce/magento/cloud.html',
  },
  adyen: { website: 'https://www.adyen.com/' },
  airbyte: { website: 'https://airbyte.com/', github: 'airbytehq/airbyte' },
  airtable: { website: 'https://www.airtable.com/' },
  algolia: { website: 'https://www.algolia.com/' },
  alibabacloud: { website: 'https://www.alibabacloud.com/' },
  alpinejs: { website: 'https://alpinejs.dev/', github: 'alpinejs/alpine' },
  amplitude: { website: 'https://amplitude.com/' },
  angular: { website: 'https://angular.io/', github: 'angular/angular' },
  ansible: { website: 'https://www.ansible.com/', github: 'ansible/ansible' },
  anthropic: { website: 'https://www.anthropic.com/' },
  apache_airflow: { website: 'https://airflow.apache.org/', github: 'apache/airflow' },
  apache_cassandra: {
    website: 'https://cassandra.apache.org/_/index.html',
    github: 'apache/cassandra',
  },
  apache_couchdb: { website: 'https://couchdb.apache.org/', github: 'apache/couchdb' },
  apache_flink: { website: 'https://flink.apache.org/', github: 'apache/flink' },
  apache_hadoop: { website: 'https://hadoop.apache.org/', github: 'apache/hadoop' },
  apache_hive: { website: 'https://hive.apache.org/', github: 'apache/hive' },
  apache_iceberg: { website: 'https://iceberg.apache.org/', github: 'apache/iceberg' },
  apache_kafka: { website: 'https://kafka.apache.org/', github: 'apache/kafka' },
  apache_solr: { website: 'https://solr.apache.org/', github: 'apache/solr' },
  apache_spark: { website: 'https://spark.apache.org/', github: 'apache/spark' },
  apache_storm: { website: 'https://storm.apache.org/', github: 'apache/storm' },
  apache_thrift: { website: 'https://thrift.apache.org/', github: 'apache/thrift' },
  apiplatform: { website: 'https://api-platform.com/', github: 'api-platform/api-platform' },
  appveyor: { website: 'https://www.appveyor.com/' },
  assemble: { website: 'http://assemble.io/', github: 'assemble/assemble' },
  astro: { website: 'https://astro.build/', github: 'withastro/astro' },
  atlasgo: { website: 'https://atlasgo.io/', github: 'ariga/atlas' },
  'atlassian.bitbucket': { website: 'https://bitbucket.org/' },
  'atlassian.confluence': { website: 'https://www.atlassian.com/software/confluence' },
  'atlassian.jira': { website: 'https://www.atlassian.com/software/jira' },
  'atlassian.opsgenie': { website: 'https://www.atlassian.com/software/opsgenie' },
  'atlassian.trello': { website: 'https://trello.com/' },
  atlassian: { website: 'https://www.atlassian.com/' },
  auth0: { website: 'https://auth0.com/' },
  'aws.amplifyhosting': { website: 'https://aws.amazon.com/amplify/hosting/' },
  'aws.apigateway': { website: 'https://aws.amazon.com/api-gateway/' },
  'aws.athena': { website: 'https://aws.amazon.com/athena/' },
  'aws.bedrock': { website: 'https://aws.amazon.com/bedrock/' },
  'aws.cloudformation': { website: 'https://aws.amazon.com/cloudformation/' },
  'aws.cloudfront': { website: 'https://aws.amazon.com/cloudfront/' },
  'aws.cloudsearch': { website: 'https://aws.amazon.com/cloudsearch/' },
  'aws.cloudwatch': { website: 'https://aws.amazon.com/cloudwatch/' },
  'aws.codebuild': { website: 'https://aws.amazon.com/codebuild/' },
  'aws.documentdb': { website: 'https://aws.amazon.com/documentdb/' },
  'aws.dynamodb': { website: 'https://aws.amazon.com/dynamodb/' },
  'aws.ebs': { website: 'https://aws.amazon.com/ebs/' },
  'aws.ec2': { website: 'https://aws.amazon.com/ec2/' },
  'aws.ecr': { website: 'https://aws.amazon.com/ecr/' },
  'aws.ecs': { website: 'https://aws.amazon.com/ecs/' },
  'aws.efs': { website: 'https://aws.amazon.com/efs/' },
  'aws.eks': { website: 'https://aws.amazon.com/eks/' },
  'aws.elasticache': { website: 'https://aws.amazon.com/elasticache/' },
  'aws.fargate': { website: 'https://aws.amazon.com/fargate/' },
  'aws.glacier': { website: 'https://aws.amazon.com/glacier/' },
  'aws.glue': { website: 'https://aws.amazon.com/glue/' },
  'aws.kafka': { website: 'https://aws.amazon.com/msk/' },
  'aws.kinesis': { website: 'https://aws.amazon.com/kinesis/' },
  'aws.kms': { website: 'https://aws.amazon.com/kms/' },
  'aws.lambda': { website: 'https://aws.amazon.com/lambda/' },
  'aws.lightsail': { website: 'https://aws.amazon.com/lightsail/' },
  'aws.memorydb': { website: 'https://aws.amazon.com/memorydb/' },
  'aws.mq': { website: 'https://aws.amazon.com/amazon-mq/' },
  'aws.neptune': { website: 'https://aws.amazon.com/neptune/' },
  'aws.opensearch': { website: 'https://aws.amazon.com/opensearch-service/' },
  'aws.polly': { website: 'https://aws.amazon.com/polly/' },
  'aws.rds': { website: 'https://aws.amazon.com/rds/' },
  'aws.redshift': { website: 'https://aws.amazon.com/redshift/' },
  'aws.rekognition': { website: 'https://aws.amazon.com/rekognition/' },
  'aws.s3': { website: 'https://aws.amazon.com/s3/' },
  'aws.sagemaker': { website: 'https://aws.amazon.com/sagemaker/' },
  'aws.secretsmanager': { website: 'https://aws.amazon.com/secrets-manager/' },
  'aws.ses': { website: 'https://aws.amazon.com/ses/' },
  'aws.sfn': { website: 'https://aws.amazon.com/step-functions/' },
  'aws.sns': { website: 'https://aws.amazon.com/sns/' },
  'aws.sqs': { website: 'https://aws.amazon.com/sqs/' },
  'aws.timestream': { website: 'https://aws.amazon.com/timestream/' },
  'aws.translate': { website: 'https://aws.amazon.com/translate/' },
  aws: { website: 'https://aws.amazon.com/' },
  'azure.aks': { website: 'https://azure.microsoft.com/en-us/products/kubernetes-service/' },
  'azure.ci': { website: 'https://azure.microsoft.com/en-us/products/devops/pipelines/' }, // Assuming Azure Pipelines
  'azure.cosmosdb': { website: 'https://azure.microsoft.com/en-us/products/cosmos-db/' },
  'azure.functions': { website: 'https://azure.microsoft.com/en-us/products/functions/' },
  'azure.mariadb': { website: 'https://azure.microsoft.com/en-us/products/mariadb/' },
  'azure.mysql': { website: 'https://azure.microsoft.com/en-us/products/mysql/' },
  'azure.openai': {
    website: 'https://azure.microsoft.com/en-us/products/ai-services/openai-service/',
  },
  'azure.postgres': { website: 'https://azure.microsoft.com/en-us/products/postgresql/' },
  'azure.redis': { website: 'https://azure.microsoft.com/en-us/products/cache/' },
  'azure.sql': { website: 'https://azure.microsoft.com/en-us/products/azure-sql/database/' },
  'azure.staticwebapps': {
    website: 'https://azure.microsoft.com/en-us/products/app-service/static/',
  },
  'azure.storage': { website: 'https://azure.microsoft.com/en-us/products/storage/' },
  azure: { website: 'https://azure.microsoft.com/' },
  bash: { website: 'https://www.gnu.org/software/bash/' },
  betterstack: { website: 'https://betterstack.com/' },
  bigcommerce: { website: 'https://www.bigcommerce.com/' },
  blackfire: { website: 'https://blackfire.io/' },
  blitzjs: { website: 'https://blitzjs.com/', github: 'blitz-js/blitz' },
  bootstrap: { website: 'https://getbootstrap.com/', github: 'twbs/bootstrap' },
  box: { website: 'https://www.box.com/' },
  brevo: { website: 'https://www.brevo.com/' }, // Formerly Sendinblue
  browserstack: { website: 'https://www.browserstack.com/' },
  bytebase: { website: 'https://www.bytebase.com/', github: 'bytebase/bytebase' },
  c: { website: 'https://en.wikipedia.org/wiki/C_(programming_language)' },
  caddy: { website: 'https://caddyserver.com/', github: 'caddyserver/caddy' },
  celery: { website: 'https://docs.celeryq.dev/', github: 'celery/celery' },
  checkov: { website: 'https://www.checkov.io/', github: 'bridgecrewio/checkov' },
  chef: { website: 'https://www.chef.io/', github: 'chef/chef' },
  circleci: { website: 'https://circleci.com/' },
  cirrusci: { website: 'https://cirrus-ci.org/' },
  clerk: { website: 'https://clerk.com/' },
  clickhouse: { website: 'https://clickhouse.com/', github: 'ClickHouse/ClickHouse' },
  clicksend: { website: 'https://www.clicksend.com/' },
  'cloudbees.codeship': { website: 'https://www.cloudbees.com/products/codeship' },
  cloudbees: { website: 'https://www.cloudbees.com/' },
  'cloudflare.pages': { website: 'https://pages.cloudflare.com/' },
  'cloudflare.workers': { website: 'https://workers.cloudflare.com/' },
  cloudflare: { website: 'https://www.cloudflare.com/' },
  cockroachdb: { website: 'https://www.cockroachlabs.com/', github: 'cockroachdb/cockroach' },
  codecov: { website: 'https://about.codecov.io/' },
  codesandboxci: { website: 'https://codesandbox.io/ci' },
  cohereai: { website: 'https://cohere.com/' },
  commercetools: { website: 'https://commercetools.com/' },
  consul: { website: 'https://www.consul.io/', github: 'hashicorp/consul' },
  contenful: { website: 'https://www.contentful.com/' },
  convexdb: { website: 'https://www.convex.dev/', github: 'get-convex/convex' },
  couchbase: { website: 'https://www.couchbase.com/' },
  coveralls: { website: 'https://coveralls.io/' },
  cplusplus: { website: 'https://isocpp.org/' },
  cratedb: { website: 'https://cratedb.com/', github: 'crate/crate' },
  crowdin: { website: 'https://crowdin.com/' },
  csharp: { website: 'https://dotnet.microsoft.com/en-us/languages/csharp' },
  css: { website: 'https://www.w3.org/Style/CSS/' },
  cypressci: { website: 'https://www.cypress.io/', github: 'cypress-io/cypress' },
  d3js: { website: 'https://d3js.org/', github: 'd3/d3' },
  dart: { website: 'https://dart.dev/', github: 'dart-lang/sdk' },
  databricks: { website: 'https://www.databricks.com/' },
  datadog: { website: 'https://www.datadoghq.com/' },
  dataiku: { website: 'https://www.dataiku.com/' },
  datastax: { website: 'https://www.datastax.com/' },
  datocms: { website: 'https://www.datocms.com/' },
  deepseek: { website: 'https://www.deepseek.com/' },
  deferrun: { website: 'https://www.defer.run/' },
  deno: { website: 'https://deno.land/', github: 'denoland/deno' },
  denodeploy: { website: 'https://deno.com/deploy' },
  dependabot: { website: 'https://github.com/dependabot', github: 'dependabot/dependabot-core' },
  digitalocean: { website: 'https://www.digitalocean.com/' },
  discord: { website: 'https://discord.com/' },
  discourse: { website: 'https://www.discourse.org/', github: 'discourse/discourse' },
  docker: { website: 'https://www.docker.com/', github: 'moby/moby' },
  doctrinephp: { website: 'https://www.doctrine-project.org/', github: 'doctrine/orm' },
  docusaurus: { website: 'https://docusaurus.io/', github: 'facebook/docusaurus' },
  docusign: { website: 'https://www.docusign.com/' },
  droneci: { website: 'https://www.drone.io/', github: 'drone/drone' },
  dropbox: { website: 'https://www.dropbox.com/' },
  drupal: { website: 'https://www.drupal.org/', github: 'drupal/drupal' },
  duckdb: { website: 'https://duckdb.org/', github: 'duckdb/duckdb' },
  dynatrace: { website: 'https://www.dynatrace.com/' },
  elasticcloud: { website: 'https://www.elastic.co/cloud/' },
  elasticsearch: {
    website: 'https://www.elastic.co/elasticsearch/',
    github: 'elastic/elasticsearch',
  },
  elasticstack: { website: 'https://www.elastic.co/elastic-stack/' },
  electron: { website: 'https://www.electronjs.org/', github: 'electron/electron' },
  eleventy: { website: 'https://www.11ty.dev/', github: '11ty/eleventy' },
  elixir: { website: 'https://elixir-lang.org/', github: 'elixir-lang/elixir' },
  emberjs: { website: 'https://emberjs.com/', github: 'emberjs/ember.js' },
  equinix: { website: 'https://www.equinix.com/' },
  esbuild: { website: 'https://esbuild.github.io/', github: 'evanw/esbuild' },
  eslint: { website: 'https://eslint.org/', github: 'eslint/eslint' },
  expodev: { website: 'https://expo.dev/' },
  expojs: { website: 'https://expo.dev/', github: 'expo/expo' }, // Same as expodev
  express: { website: 'https://expressjs.com/', github: 'expressjs/express' },
  fabric: { website: 'http://www.fabfile.org/', github: 'fabric/fabric' }, // Python deployment tool
  facebook: { website: 'https://about.facebook.com/' },
  fastify: { website: 'https://fastify.dev/', github: 'fastify/fastify' },
  fastly: { website: 'https://www.fastly.com/' },
  figma: { website: 'https://www.figma.com/' },
  'firebase.firestore': { website: 'https://firebase.google.com/docs/firestore' },
  firebase: { website: 'https://firebase.google.com/' },
  flyio: { website: 'https://fly.io/' },
  flyway: { website: 'https://flywaydb.org/', github: 'redgate-oss/flyway' },
  gatsby: { website: 'https://www.gatsbyjs.com/', github: 'gatsbyjs/gatsby' },
  'gcp.aiplatform': { website: 'https://cloud.google.com/vertex-ai' }, // Renamed to Vertex AI
  'gcp.appengine': { website: 'https://cloud.google.com/appengine' },
  'gcp.artifactregistry': { website: 'https://cloud.google.com/artifact-registry' },
  'gcp.bigquery': { website: 'https://cloud.google.com/bigquery' },
  'gcp.bigtable': { website: 'https://cloud.google.com/bigtable' },
  'gcp.cloudbuild': { website: 'https://cloud.google.com/build' },
  'gcp.cloudrun': { website: 'https://cloud.google.com/run' },
  'gcp.containerregistry': { website: 'https://cloud.google.com/container-registry' }, // Being replaced by Artifact Registry
  'gcp.dataflow': { website: 'https://cloud.google.com/dataflow' },
  'gcp.dataproc': { website: 'https://cloud.google.com/dataproc' },
  'gcp.datastore': { website: 'https://cloud.google.com/datastore' }, // Now Firestore in Datastore mode
  'gcp.dialogflow': { website: 'https://cloud.google.com/dialogflow' },
  'gcp.dns': { website: 'https://cloud.google.com/dns' },
  'gcp.functions': { website: 'https://cloud.google.com/functions' },
  'gcp.gce': { website: 'https://cloud.google.com/compute' },
  'gcp.gcs': { website: 'https://cloud.google.com/storage' },
  'gcp.gke': { website: 'https://cloud.google.com/kubernetes-engine' },
  'gcp.kms': { website: 'https://cloud.google.com/kms' },
  'gcp.language': { website: 'https://cloud.google.com/natural-language' },
  'gcp.logging': { website: 'https://cloud.google.com/logging' },
  'gcp.maps': { website: 'https://developers.google.com/maps' },
  'gcp.memorystore': { website: 'https://cloud.google.com/memorystore' },
  'gcp.pubsub': { website: 'https://cloud.google.com/pubsub' },
  'gcp.secretmanager': { website: 'https://cloud.google.com/secret-manager' },
  'gcp.spanner': { website: 'https://cloud.google.com/spanner' },
  'gcp.speech': { website: 'https://cloud.google.com/speech-to-text' },
  'gcp.sql': { website: 'https://cloud.google.com/sql' },
  'gcp.tasks': { website: 'https://cloud.google.com/tasks' },
  'gcp.translate': { website: 'https://cloud.google.com/translate' },
  'gcp.vision': { website: 'https://cloud.google.com/vision' },
  gcp: { website: 'https://cloud.google.com/' },
  geminiai: { website: 'https://gemini.google.com/' },
  ghost: { website: 'https://ghost.org/', github: 'TryGhost/Ghost' },
  gitbook: { website: 'https://www.gitbook.com/' },
  gitguardian: { website: 'https://www.gitguardian.com/' },
  'github.actions': { website: 'https://github.com/features/actions', github: 'actions/runner' },
  'github.pages': { website: 'https://pages.github.com/', github: 'github/pages-gem' },
  github: { website: 'https://github.com/', github: 'github/roadmap' }, // Using roadmap as a placeholder public repo
  'gitlab.ci': { website: 'https://docs.gitlab.com/ee/ci/' },
  gitlab: { website: 'https://about.gitlab.com/', github: 'gitlab-org/gitlab' },
  goacmelego: { website: 'https://go-acme.github.io/lego/', github: 'go-acme/lego' },
  golang: { website: 'https://go.dev/', github: 'golang/go' },
  golangcilint: { website: 'https://golangci-lint.run/', github: 'golangci/golangci-lint' },
  googleanalytics: { website: 'https://analytics.google.com/' },
  gradio: { website: 'https://www.gradio.app/', github: 'gradio-app/gradio' },
  grafana: { website: 'https://grafana.com/', github: 'grafana/grafana' },
  gridsome: { website: 'https://gridsome.org/', github: 'gridsome/gridsome' },
  groq: { website: 'https://groq.com/' },
  haproxy: { website: 'https://www.haproxy.org/', github: 'haproxy/haproxy' },
  hashicorp_vault: { website: 'https://www.vaultproject.io/', github: 'hashicorp/vault' },
  healthchecksio: { website: 'https://healthchecks.io/', github: 'healthchecks/healthchecks' },
  helm: { website: 'https://helm.sh/', github: 'helm/helm' },
  heroku: { website: 'https://www.heroku.com/' },
  hexojs: { website: 'https://hexo.io/', github: 'hexojs/hexo' },
  hotjar: { website: 'https://www.hotjar.com/' },
  html: { website: 'https://html.spec.whatwg.org/' },
  httpd: { website: 'https://httpd.apache.org/', github: 'apache/httpd' },
  hubspot: { website: 'https://www.hubspot.com/' },
  huggingface: { website: 'https://huggingface.co/' },
  hugo: { website: 'https://gohugo.io/', github: 'gohugoio/hugo' },
  hyperdx: { website: 'https://hyperdx.io/', github: 'hyperdxio/hyperdx' },
  hypertune: { website: 'https://hypertune.com/', github: 'hypertune/hypertune' },
  ibmcloud: { website: 'https://www.ibm.com/cloud' },
  iftt: { website: 'https://ifttt.com/' },
  influxdb: { website: 'https://www.influxdata.com/', github: 'influxdata/influxdb' },
  intercom: { website: 'https://www.intercom.com/' },
  intuit: { website: 'https://www.intuit.com/' },
  java: { website: 'https://www.java.com/', github: 'openjdk/jdk' },
  javascript: { website: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript' },
  jekyll: { website: 'https://jekyllrb.com/', github: 'jekyll/jekyll' },
  jenkins: { website: 'https://www.jenkins.io/', github: 'jenkinsci/jenkins' },
  jest: { website: 'https://jestjs.io/', github: 'jestjs/jest' },
  joomla: { website: 'https://www.joomla.org/', github: 'joomla/joomla-cms' },
  k6: { website: 'https://k6.io/', github: 'grafana/k6' },
  kentico: { website: 'https://kentico.com/' },
  kibana: { website: 'https://www.elastic.co/kibana/', github: 'elastic/kibana' },
  klarna: { website: 'https://www.klarna.com/' },
  klaviyo: { website: 'https://www.klaviyo.com/' },
  koa: { website: 'https://koajs.com/', github: 'koajs/koa' },
  koalaanalytics: { website: 'https://koala.io/' }, // Assuming koala.io
  kong: { website: 'https://konghq.com/', github: 'Kong/kong' },
  kotlin: { website: 'https://kotlinlang.org/', github: 'JetBrains/kotlin' },
  koyeb: { website: 'https://www.koyeb.com/' },
  kubernetes: { website: 'https://kubernetes.io/', github: 'kubernetes/kubernetes' },
  lago: { website: 'https://www.getlago.com/', github: 'getlago/lago' },
  laravel: { website: 'https://laravel.com/', github: 'laravel/laravel' },
  launchdarkly: { website: 'https://launchdarkly.com/' },
  lemonsqueezy: { website: 'https://www.lemonsqueezy.com/' },
  libsql: { website: 'https://turso.tech/', github: 'libsql/libsql' }, // Associated with Turso
  lighthouse: {
    website: 'https://developer.chrome.com/docs/lighthouse/',
    github: 'GoogleChrome/lighthouse',
  },
  linear: { website: 'https://linear.app/' },
  liquibase: { website: 'https://www.liquibase.org/', github: 'liquibase/liquibase' },
  logrocket: { website: 'https://logrocket.com/' },
  logsnag: { website: 'https://logsnag.com/' },
  logstash: { website: 'https://www.elastic.co/logstash/', github: 'elastic/logstash' },
  magento: {
    website: 'https://business.adobe.com/products/commerce/magento/magento-open-source.html',
  }, // Now Adobe Commerce / Magento Open Source
  mailchimp: { website: 'https://mailchimp.com/' },
  mailgun: { website: 'https://www.mailgun.com/' },
  mailhog: { website: 'https://github.com/mailhog/MailHog', github: 'mailhog/MailHog' },
  mailjet: { website: 'https://www.mailjet.com/' },
  mariadb: { website: 'https://mariadb.org/', github: 'MariaDB/server' },
  matomo: { website: 'https://matomo.org/', github: 'matomo-org/matomo' },
  mattermost: { website: 'https://mattermost.com/', github: 'mattermost/mattermost' },
  meilisearch: { website: 'https://www.meilisearch.com/', github: 'meilisearch/meilisearch' },
  meilisearchcloud: { website: 'https://cloud.meilisearch.com/' },
  memcached: { website: 'https://memcached.org/', github: 'memcached/memcached' },
  meteorjs: { website: 'https://www.meteor.com/', github: 'meteor/meteor' },
  milvusdb: { website: 'https://milvus.io/', github: 'milvus-io/milvus' },
  mistralai: { website: 'https://mistral.ai/' },
  mithriljs: { website: 'https://mithril.js.org/', github: 'MithrilJS/mithril.js' },
  mixpanel: { website: 'https://mixpanel.com/' },
  mongodb: { website: 'https://www.mongodb.com/' },
  mongodbatlas: { website: 'https://www.mongodb.com/cloud/atlas' },
  mongoexpress: {
    website: 'https://github.com/mongo-express/mongo-express',
    github: 'mongo-express/mongo-express',
  },
  mysql: { website: 'https://www.mysql.com/', github: 'mysql/mysql-server' },
  nango: { website: 'https://www.nango.dev/', github: 'NangoHQ/nango' },
  nats: { website: 'https://nats.io/', github: 'nats-io/nats-server' },
  neo4j: { website: 'https://neo4j.com/', github: 'neo4j/neo4j' },
  neondb: { website: 'https://neon.tech/', github: 'neondatabase/neon' },
  nestjs: { website: 'https://nestjs.com/', github: 'nestjs/nest' },
  netlify: { website: 'https://www.netlify.com/' },
  newrelic: { website: 'https://newrelic.com/' },
  nextcloud: { website: 'https://nextcloud.com/', github: 'nextcloud/server' },
  nextjs: { website: 'https://nextjs.org/', github: 'vercel/next.js' },
  nginx: { website: 'https://nginx.org/' }, // Official repo is Mercurial, GitHub is a mirror
  nodejs: { website: 'https://nodejs.org/', github: 'nodejs/node' },
  notion: { website: 'https://www.notion.so/' },
  novu: { website: 'https://novu.co/', github: 'novuhq/novu' },
  nuxtjs: { website: 'https://nuxtjs.org/', github: 'nuxt/nuxt' },
  nxcloud: { website: 'https://nx.app/' },
  nxjs: { website: 'https://nx.dev/', github: 'nrwl/nx' },
  oceanbase: { website: 'https://en.oceanbase.com/', github: 'oceanbase/oceanbase' },
  okta: { website: 'https://www.okta.com/' },
  onlineornot: { website: 'https://onlineornot.com/' },
  openai: { website: 'https://openai.com/' },
  optimizely: { website: 'https://www.optimizely.com/' },
  oraclecloud: { website: 'https://www.oracle.com/cloud/' },
  'ovh.database': { website: 'https://www.ovhcloud.com/en/public-cloud/databases/' },
  'ovh.dedicated': { website: 'https://www.ovhcloud.com/en/bare-metal/' },
  'ovh.kubernetes': { website: 'https://www.ovhcloud.com/en/public-cloud/kubernetes/' },
  'ovh.storage': { website: 'https://www.ovhcloud.com/en/public-cloud/storage/' },
  'ovh.vps': { website: 'https://www.ovhcloud.com/en/vps/' },
  ovh: { website: 'https://www.ovhcloud.com/' },
  pagerduty: { website: 'https://www.pagerduty.com/' },
  papertrail: { website: 'https://www.papertrail.com/' },
  payloadcms: { website: 'https://payloadcms.com/', github: 'payloadcms/payload' },
  paypal: { website: 'https://www.paypal.com/' },
  percona: { website: 'https://www.percona.com/' },
  perplexityai: { website: 'https://www.perplexity.ai/' },
  phaserjs: { website: 'https://phaser.io/', github: 'photonstorm/phaser' },
  php: { website: 'https://www.php.net/', github: 'php/php-src' },
  phppest: { website: 'https://pestphp.com/', github: 'pestphp/pest' },
  phpstan: { website: 'https://phpstan.org/', github: 'phpstan/phpstan' },
  phpunit: { website: 'https://phpunit.de/', github: 'sebastianbergmann/phpunit' },
  pingdom: { website: 'https://www.pingdom.com/' },
  pirschanalytics: { website: 'https://pirsch.io/' },
  placekit: { website: 'https://placekit.io/' },
  planetscale: { website: 'https://planetscale.com/' },
  platformsh: { website: 'https://platform.sh/' },
  plausible: { website: 'https://plausible.io/', github: 'plausible/analytics' },
  playwright: { website: 'https://playwright.dev/', github: 'microsoft/playwright' },
  pnpm: { website: 'https://pnpm.io/', github: 'pnpm/pnpm' },
  postgresql: { website: 'https://www.postgresql.org/', github: 'postgres/postgres' },
  postgrest: { website: 'https://postgrest.org/', github: 'PostgREST/postgrest' },
  posthog: { website: 'https://posthog.com/', github: 'PostHog/posthog' },
  postman: { website: 'https://www.postman.com/' },
  postmark: { website: 'https://postmarkapp.com/' },
  powershell: {
    website: 'https://learn.microsoft.com/en-us/powershell/',
    github: 'PowerShell/PowerShell',
  },
  preactjs: { website: 'https://preactjs.com/', github: 'preactjs/preact' },
  prestashop: { website: 'https://www.prestashop.com/', github: 'PrestaShop/PrestaShop' },
  prettier: { website: 'https://prettier.io/', github: 'prettier/prettier' },
  prisma: { website: 'https://www.prisma.io/', github: 'prisma/prisma' },
  prismacloud: { website: 'https://www.paloaltonetworks.com/prisma/cloud' },
  prometheus: { website: 'https://prometheus.io/', github: 'prometheus/prometheus' },
  puppeteer: { website: 'https://pptr.dev/', github: 'puppeteer/puppeteer' },
  python: {
    website: 'https://www.python.org/',
    github: 'python/cpython',
    iconURL: 'https://avatars.githubusercontent.com/u/1525981?s=200&v=4',
  },
  pytorch: { website: 'https://pytorch.org/', github: 'pytorch/pytorch' },
  qdrant: { website: 'https://qdrant.tech/', github: 'qdrant/qdrant' },
  'qovery.cluster': { website: 'https://www.qovery.com/cluster' },
  'qovery.database': { website: 'https://www.qovery.com/database' },
  qovery: { website: 'https://www.qovery.com/' },
  questdb: { website: 'https://questdb.io/', github: 'questdb/questdb' },
  rabbitmq: { website: 'https://www.rabbitmq.com/', github: 'rabbitmq/rabbitmq-server' },
  'railway.mongodb': { website: 'https://railway.app/template/mongodb' },
  'railway.mysql': { website: 'https://railway.app/template/mysql' },
  'railway.postgres': { website: 'https://railway.app/template/postgresql' },
  'railway.redis': { website: 'https://railway.app/template/redis' },
  railway: { website: 'https://railway.app/' },
  react: { website: 'https://react.dev/', github: 'facebook/react' },
  reactemail: { website: 'https://react.email/', github: 'resend/react-email' },
  redis: { website: 'https://redis.io/', github: 'redis/redis' },
  redwoodjs: { website: 'https://redwoodjs.com/', github: 'redwoodjs/redwood' },
  refinedev: { website: 'https://refine.dev/', github: 'refinedev/refine' },
  relativeci: { website: 'https://relative-ci.com/' },
  remixrun: { website: 'https://remix.run/', github: 'remix-run/remix' },
  render: { website: 'https://render.com/' },
  renovate: { website: 'https://github.com/renovatebot/renovate', github: 'renovatebot/renovate' },
  'replit.database': { website: 'https://docs.replit.com/hosting/databases/replit-database' },
  'replit.postgres': { website: 'https://docs.replit.com/hosting/databases/postgresql-databases' },
  replit: { website: 'https://replit.com/' },
  resend: { website: 'https://resend.com/' },
  rethinkdb: { website: 'https://rethinkdb.com/', github: 'rethinkdb/rethinkdb' },
  rollbar: { website: 'https://rollbar.com/' },
  rollup: { website: 'https://rollupjs.org/', github: 'rollup/rollup' },
  ruby: { website: 'https://www.ruby-lang.org/', github: 'ruby/ruby' },
  rust: { website: 'https://www.rust-lang.org/', github: 'rust-lang/rust' },
  salesforce: { website: 'https://www.salesforce.com/' },
  sanity: { website: 'https://www.sanity.io/', github: 'sanity-io/sanity' },
  sap: { website: 'https://www.sap.com/' },
  sas: { website: 'https://www.sas.com/' },
  'scaleway.container': { website: 'https://www.scaleway.com/en/containers/' },
  'scaleway.database': { website: 'https://www.scaleway.com/en/database/' },
  'scaleway.documentdb': { website: 'https://www.scaleway.com/en/document-database/' },
  'scaleway.elasticmetal': { website: 'https://www.scaleway.com/en/elastic-metal/' },
  'scaleway.function': { website: 'https://www.scaleway.com/en/serverless-functions/' },
  'scaleway.kubernetes': { website: 'https://www.scaleway.com/en/kubernetes-kapsule/' },
  'scaleway.mq': { website: 'https://www.scaleway.com/en/managed-message-queues/' },
  'scaleway.redis': { website: 'https://www.scaleway.com/en/redis-database/' },
  'scaleway.secretmanager': { website: 'https://www.scaleway.com/en/secret-manager/' },
  'scaleway.storage': { website: 'https://www.scaleway.com/en/object-storage/' },
  scaleway: { website: 'https://www.scaleway.com/' },
  scoutapm: { website: 'https://scoutapm.com/' },
  scss: { website: 'https://sass-lang.com/', github: 'sass/sass' }, // Sass is the parent technology
  selenium: { website: 'https://www.selenium.dev/', github: 'SeleniumHQ/selenium' },
  sendgrid: { website: 'https://sendgrid.com/' },
  sentry: { website: 'https://sentry.io/', github: 'getsentry/sentry' },
  sequelize: { website: 'https://sequelize.org/', github: 'sequelize/sequelize' },
  servicenow: { website: 'https://www.servicenow.com/' },
  'shopify.hydrogen': { website: 'https://hydrogen.shopify.dev/' },
  shopify: { website: 'https://www.shopify.com/' },
  signoz: { website: 'https://signoz.io/', github: 'SigNoz/signoz' },
  'sitecore.xmlcloud': { website: 'https://www.sitecore.com/products/xm-cloud' },
  sitecore: { website: 'https://www.sitecore.com/' },
  slack: { website: 'https://slack.com/' },
  snowflake: { website: 'https://www.snowflake.com/' },
  snyk: { website: 'https://snyk.io/' },
  socketio: { website: 'https://socket.io/', github: 'socketio/socket.io' },
  solidjs: { website: 'https://www.solidjs.com/', github: 'solidjs/solid' },
  sonarcloud: { website: 'https://sonarcloud.io/' },
  sonarlint: { website: 'https://www.sonarsource.com/products/sonarlint/' },
  sonarqube: { website: 'https://www.sonarsource.com/products/sonarqube/' },
  splitio: { website: 'https://www.split.io/' },
  splunk: { website: 'https://www.splunk.com/' },
  sqlite: { website: 'https://www.sqlite.org/', github: 'sqlite/sqlite' }, // Mirror, main is Fossil
  sqreen: { website: 'https://www.datadoghq.com/product/application-security-monitoring/' }, // Acquired by Datadog
  squarespace: { website: 'https://www.squarespace.com/' },
  squareup: { website: 'https://squareup.com/' },
  storybook: { website: 'https://storybook.js.org/', github: 'storybookjs/storybook' },
  strapi: { website: 'https://strapi.io/', github: 'strapi/strapi' },
  stripe: { website: 'https://stripe.com/' },
  styleci: { website: 'https://styleci.io/' },
  stylelint: { website: 'https://stylelint.io/', github: 'stylelint/stylelint' },
  'supabase.auth': { website: 'https://supabase.com/docs/guides/auth' },
  'supabase.functions': { website: 'https://supabase.com/docs/guides/functions' },
  'supabase.postgres': { website: 'https://supabase.com/docs/guides/database' },
  'supabase.realtime': { website: 'https://supabase.com/docs/guides/realtime' },
  'supabase.storage': { website: 'https://supabase.com/docs/guides/storage' },
  supabase: { website: 'https://supabase.com/', github: 'supabase/supabase' },
  surrealdb: { website: 'https://surrealdb.com/', github: 'surrealdb/surrealdb' },
  sveltejs: { website: 'https://svelte.dev/', github: 'sveltejs/svelte' },
  swift: { website: 'https://www.swift.org/', github: 'apple/swift' },
  symfony: { website: 'https://symfony.com/', github: 'symfony/symfony' },
  tailscale: { website: 'https://tailscale.com/' },
  tailwind: { website: 'https://tailwindcss.com/', github: 'tailwindlabs/tailwindcss' },
  tanstackstart: { website: 'https://tanstack.com/start/latest', github: 'TanStack/start' },
  tdengine: { website: 'https://tdengine.com/', github: 'taosdata/TDengine' },
  teamcity: { website: 'https://www.jetbrains.com/teamcity/' },
  teamspeak: { website: 'https://www.teamspeak.com/' },
  telegraf: {
    website: 'https://www.influxdata.com/time-series-platform/telegraf/',
    github: 'influxdata/telegraf',
  },
  telegram: { website: 'https://telegram.org/' },
  tencentcloud: { website: 'https://www.tencentcloud.com/' },
  tensorflow: { website: 'https://www.tensorflow.org/', github: 'tensorflow/tensorflow' },
  terraform: { website: 'https://www.terraform.io/', github: 'hashicorp/terraform' },
  terragrunt: { website: 'https://terragrunt.gruntwork.io/', github: 'gruntwork-io/terragrunt' },
  tidb: { website: 'https://pingcap.com/products/tidb/', github: 'pingcap/tidb' },
  timescaledb: { website: 'https://www.timescale.com/', github: 'timescale/timescaledb' },
  tinybird: { website: 'https://www.tinybird.co/' },
  traefik: { website: 'https://traefik.io/', github: 'traefik/traefik' },
  travisci: { website: 'https://www.travis-ci.com/' },
  trufflesecurity: { website: 'https://trufflesecurity.com/' },
  turborepo: { website: 'https://turbo.build/repo', github: 'vercel/turbo' },
  tursodb: { website: 'https://turso.tech/', github: 'tursodatabase/libsql' }, // Same as libsql
  twigphp: { website: 'https://twig.symfony.com/', github: 'twigphp/Twig' },
  twilio: { website: 'https://www.twilio.com/' },
  twitter: { website: 'https://twitter.com/' },
  typescript: { website: 'https://www.typescriptlang.org/', github: 'microsoft/TypeScript' },
  typesense: { website: 'https://typesense.org/', github: 'typesense/typesense' },
  typesensecloud: { website: 'https://cloud.typesense.org/' },
  'upstash.kafka': { website: 'https://upstash.com/kafka' },
  'upstash.qstash': { website: 'https://upstash.com/qstash' },
  'upstash.redis': { website: 'https://upstash.com/redis' },
  upstash: { website: 'https://upstash.com/' },
  uptimekuma: {
    website: 'https://github.com/louislam/uptime-kuma',
    github: 'louislam/uptime-kuma',
  },
  vale: { website: 'https://vale.sh/', github: 'errata-ai/vale' },
  'vercel.ai': { website: 'https://vercel.com/ai' },
  'vercel.analytics': { website: 'https://vercel.com/analytics' },
  'vercel.blob': { website: 'https://vercel.com/blob' },
  'vercel.edge': { website: 'https://vercel.com/edge' },
  'vercel.kv': { website: 'https://vercel.com/kv' },
  'vercel.postgres': { website: 'https://vercel.com/postgres' },
  vercel: { website: 'https://vercel.com/' },
  veriff: { website: 'https://www.veriff.com/' },
  vialink: { website: 'https://vialink.fr/' },
  victoriametrics: {
    website: 'https://victoriametrics.com/',
    github: 'VictoriaMetrics/VictoriaMetrics',
  },
  vite: { website: 'https://vitejs.dev/', github: 'vitejs/vite' },
  vue: { website: 'https://vuejs.org/', github: 'vuejs/vue' },
  wasp: { website: 'https://wasp-lang.dev/', github: 'wasp-lang/wasp' },
  webflow: { website: 'https://webflow.com/' },
  webpack: { website: 'https://webpack.js.org/', github: 'webpack/webpack' },
  wiz: { website: 'https://www.wiz.io/' },
  woocommerce: { website: 'https://woocommerce.com/', github: 'woocommerce/woocommerce' },
  wordpress: { website: 'https://wordpress.org/', github: 'WordPress/wordpress-develop' }, // Dev repo
  workos: { website: 'https://workos.com/' },
  xai: { website: 'https://x.ai/' },
  yarn: { website: 'https://yarnpkg.com/', github: 'yarnpkg/berry' },
  yii2: { website: 'https://www.yiiframework.com/', github: 'yiisoft/yii2' },
  yousign: { website: 'https://yousign.com/' },
  zapier: { website: 'https://zapier.com/' },
  zendesk: { website: 'https://www.zendesk.com/' },
  zig: { website: 'https://ziglang.org/', github: 'ziglang/zig' },
  zipkin: { website: 'https://zipkin.io/', github: 'openzipkin/zipkin' },
  zookeeper: { website: 'https://zookeeper.apache.org/', github: 'apache/zookeeper' },
  zoom: { website: 'https://zoom.us/' },
  zuora: { website: 'https://www.zuora.com/' },
};

const extendedListTech = listTech.map((tech) => {
  const extended = extendedInfo[tech.key]!;

  return {
    ...tech,
    ...extended,
  };
});

export { extendedListTech };
