import { listTech } from '@specfy/stack-analyser/dist/common/techs.generated.js';

import type { AllowedKeys, TechItem } from '@specfy/stack-analyser';

export type TechItemExtended = { website: string } & TechItem;

export const colors: [
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
] = [
  'hsl(200.66deg 52.14% 77.06%)',
  'hsl(204.16deg 70.62% 41.37%)',
  'hsl(91.76deg 57.05% 70.78%)',
  'hsl(116.38deg 56.86% 40%)',
  'hsl(0.61deg 92.45% 79.22%)',
  'hsl(359.4deg 79.45% 49.61%)',
  'hsl(33.8deg 97.26% 71.37%)',
  'hsl(29.88deg 100% 50%)',
  'hsl(280deg 30.51% 76.86%)',
  'hsl(269.03deg 43.26% 42.16%)',
  'hsl(60deg 100% 80%)',
  'hsl(21.46deg 63.13% 42.55%)',
];

export interface ExtendedTechItem {
  website?: string;
  github?: string;
  iconURL?: string;
  color: string;
}

// Hardcode the website URL for each entry
const extendedInfo: Record<AllowedKeys, ExtendedTechItem> = {
  adminer: { website: 'https://www.adminer.org/', color: colors[0] },
  adobe: { website: 'https://www.adobe.com/', color: colors[1] },
  adobecommercecloud: {
    website: 'https://business.adobe.com/products/commerce/magento/cloud.html',
    color: colors[2],
  },
  adyen: { website: 'https://www.adyen.com/', color: colors[3] },
  airbyte: { website: 'https://airbyte.com/', github: 'airbytehq/airbyte', color: colors[4] },
  airtable: { website: 'https://www.airtable.com/', color: colors[5] },
  algolia: { website: 'https://www.algolia.com/', color: colors[6] },
  alibabacloud: { website: 'https://www.alibabacloud.com/', color: colors[7] },
  alpinejs: { website: 'https://alpinejs.dev/', github: 'alpinejs/alpine', color: colors[7] },
  amplitude: { website: 'https://amplitude.com/', color: colors[9] },
  angular: { website: 'https://angular.io/', github: 'angular/angular', color: colors[0] },
  ansible: { website: 'https://www.ansible.com/', github: 'ansible/ansible', color: colors[1] },
  anthropic: { website: 'https://www.anthropic.com/', color: colors[2] },
  apache_airflow: {
    website: 'https://airflow.apache.org/',
    github: 'apache/airflow',
    color: colors[3],
  },
  apache_cassandra: {
    website: 'https://cassandra.apache.org/_/index.html',
    github: 'apache/cassandra',
    color: colors[4],
  },
  apache_couchdb: {
    website: 'https://couchdb.apache.org/',
    github: 'apache/couchdb',
    color: colors[5],
  },
  apache_flink: { website: 'https://flink.apache.org/', github: 'apache/flink', color: colors[6] },
  apache_hadoop: {
    website: 'https://hadoop.apache.org/',
    github: 'apache/hadoop',
    color: colors[7],
  },
  apache_hive: { website: 'https://hive.apache.org/', github: 'apache/hive', color: colors[7] },
  apache_iceberg: {
    website: 'https://iceberg.apache.org/',
    github: 'apache/iceberg',
    color: colors[9],
  },
  apache_kafka: { website: 'https://kafka.apache.org/', github: 'apache/kafka', color: colors[0] },
  apache_solr: { website: 'https://solr.apache.org/', github: 'apache/solr', color: colors[1] },
  apache_spark: { website: 'https://spark.apache.org/', github: 'apache/spark', color: colors[2] },
  apache_storm: { website: 'https://storm.apache.org/', github: 'apache/storm', color: colors[3] },
  apache_thrift: {
    website: 'https://thrift.apache.org/',
    github: 'apache/thrift',
    color: colors[4],
  },
  apiplatform: {
    website: 'https://api-platform.com/',
    github: 'api-platform/api-platform',
    color: colors[5],
  },
  appveyor: { website: 'https://www.appveyor.com/', color: colors[6] },
  assemble: { website: 'http://assemble.io/', github: 'assemble/assemble', color: colors[7] },
  astro: { website: 'https://astro.build/', github: 'withastro/astro', color: colors[7] },
  atlasgo: { website: 'https://atlasgo.io/', github: 'ariga/atlas', color: colors[9] },
  'atlassian.bitbucket': { website: 'https://bitbucket.org/', color: colors[0] },
  'atlassian.confluence': {
    website: 'https://www.atlassian.com/software/confluence',
    color: colors[1],
  },
  'atlassian.jira': { website: 'https://www.atlassian.com/software/jira', color: colors[2] },
  'atlassian.opsgenie': {
    website: 'https://www.atlassian.com/software/opsgenie',
    color: colors[3],
  },
  'atlassian.trello': { website: 'https://trello.com/', color: colors[4] },
  atlassian: { website: 'https://www.atlassian.com/', color: colors[5] },
  auth0: { website: 'https://auth0.com/', color: colors[6] },
  'aws.amplifyhosting': { website: 'https://aws.amazon.com/amplify/hosting/', color: colors[7] },
  'aws.apigateway': { website: 'https://aws.amazon.com/api-gateway/', color: colors[7] },
  'aws.athena': { website: 'https://aws.amazon.com/athena/', color: colors[9] },
  'aws.bedrock': { website: 'https://aws.amazon.com/bedrock/', color: colors[0] },
  'aws.cloudformation': { website: 'https://aws.amazon.com/cloudformation/', color: colors[1] },
  'aws.cloudfront': { website: 'https://aws.amazon.com/cloudfront/', color: colors[2] },
  'aws.cloudsearch': { website: 'https://aws.amazon.com/cloudsearch/', color: colors[3] },
  'aws.cloudwatch': { website: 'https://aws.amazon.com/cloudwatch/', color: colors[4] },
  'aws.codebuild': { website: 'https://aws.amazon.com/codebuild/', color: colors[5] },
  'aws.documentdb': { website: 'https://aws.amazon.com/documentdb/', color: colors[6] },
  'aws.dynamodb': { website: 'https://aws.amazon.com/dynamodb/', color: colors[7] },
  'aws.ebs': { website: 'https://aws.amazon.com/ebs/', color: colors[7] },
  'aws.ec2': { website: 'https://aws.amazon.com/ec2/', color: colors[9] },
  'aws.ecr': { website: 'https://aws.amazon.com/ecr/', color: colors[0] },
  'aws.ecs': { website: 'https://aws.amazon.com/ecs/', color: colors[1] },
  'aws.efs': { website: 'https://aws.amazon.com/efs/', color: colors[2] },
  'aws.eks': { website: 'https://aws.amazon.com/eks/', color: colors[3] },
  'aws.elasticache': { website: 'https://aws.amazon.com/elasticache/', color: colors[4] },
  'aws.fargate': { website: 'https://aws.amazon.com/fargate/', color: colors[5] },
  'aws.glacier': { website: 'https://aws.amazon.com/glacier/', color: colors[6] },
  'aws.glue': { website: 'https://aws.amazon.com/glue/', color: colors[7] },
  'aws.kafka': { website: 'https://aws.amazon.com/msk/', color: colors[7] },
  'aws.kinesis': { website: 'https://aws.amazon.com/kinesis/', color: colors[9] },
  'aws.kms': { website: 'https://aws.amazon.com/kms/', color: colors[0] },
  'aws.lambda': { website: 'https://aws.amazon.com/lambda/', color: colors[1] },
  'aws.lightsail': { website: 'https://aws.amazon.com/lightsail/', color: colors[2] },
  'aws.memorydb': { website: 'https://aws.amazon.com/memorydb/', color: colors[3] },
  'aws.mq': { website: 'https://aws.amazon.com/amazon-mq/', color: colors[4] },
  'aws.neptune': { website: 'https://aws.amazon.com/neptune/', color: colors[5] },
  'aws.opensearch': { website: 'https://aws.amazon.com/opensearch-service/', color: colors[6] },
  'aws.polly': { website: 'https://aws.amazon.com/polly/', color: colors[7] },
  'aws.rds': { website: 'https://aws.amazon.com/rds/', color: colors[7] },
  'aws.redshift': { website: 'https://aws.amazon.com/redshift/', color: colors[9] },
  'aws.rekognition': { website: 'https://aws.amazon.com/rekognition/', color: colors[0] },
  'aws.s3': { website: 'https://aws.amazon.com/s3/', color: colors[1] },
  'aws.sagemaker': { website: 'https://aws.amazon.com/sagemaker/', color: colors[2] },
  'aws.secretsmanager': { website: 'https://aws.amazon.com/secrets-manager/', color: colors[3] },
  'aws.ses': { website: 'https://aws.amazon.com/ses/', color: colors[4] },
  'aws.sfn': { website: 'https://aws.amazon.com/step-functions/', color: colors[5] },
  'aws.sns': { website: 'https://aws.amazon.com/sns/', color: colors[6] },
  'aws.sqs': { website: 'https://aws.amazon.com/sqs/', color: colors[7] },
  'aws.timestream': { website: 'https://aws.amazon.com/timestream/', color: colors[7] },
  'aws.translate': { website: 'https://aws.amazon.com/translate/', color: colors[9] },
  aws: { website: 'https://aws.amazon.com/', color: colors[0] },
  'azure.aks': {
    website: 'https://azure.microsoft.com/en-us/products/kubernetes-service/',
    color: colors[1],
  },
  'azure.ci': {
    website: 'https://azure.microsoft.com/en-us/products/devops/pipelines/',
    color: colors[2],
  }, // Assuming Azure Pipelines
  'azure.cosmosdb': {
    website: 'https://azure.microsoft.com/en-us/products/cosmos-db/',
    color: colors[3],
  },
  'azure.functions': {
    website: 'https://azure.microsoft.com/en-us/products/functions/',
    color: colors[4],
  },
  'azure.mariadb': {
    website: 'https://azure.microsoft.com/en-us/products/mariadb/',
    color: colors[5],
  },
  'azure.mysql': {
    website: 'https://azure.microsoft.com/en-us/products/mysql/',
    color: colors[6],
  },
  'azure.openai': {
    website: 'https://azure.microsoft.com/en-us/products/ai-services/openai-service/',
    color: colors[7],
  },
  'azure.postgres': {
    website: 'https://azure.microsoft.com/en-us/products/postgresql/',
    color: colors[7],
  },
  'azure.redis': {
    website: 'https://azure.microsoft.com/en-us/products/cache/',
    color: colors[9],
  },
  'azure.sql': {
    website: 'https://azure.microsoft.com/en-us/products/azure-sql/database/',
    color: colors[0],
  },
  'azure.staticwebapps': {
    website: 'https://azure.microsoft.com/en-us/products/app-service/static/',
    color: colors[1],
  },
  'azure.storage': {
    website: 'https://azure.microsoft.com/en-us/products/storage/',
    color: colors[2],
  },
  azure: { website: 'https://azure.microsoft.com/', color: colors[3] },
  bash: { website: 'https://www.gnu.org/software/bash/', color: colors[4] },
  betterstack: { website: 'https://betterstack.com/', color: colors[5] },
  bigcommerce: { website: 'https://www.bigcommerce.com/', color: colors[6] },
  blackfire: { website: 'https://blackfire.io/', color: colors[7] },
  blitzjs: { website: 'https://blitzjs.com/', github: 'blitz-js/blitz', color: colors[7] },
  bootstrap: { website: 'https://getbootstrap.com/', github: 'twbs/bootstrap', color: colors[9] },
  box: { website: 'https://www.box.com/', color: colors[0] },
  brevo: { website: 'https://www.brevo.com/', color: colors[1] }, // Formerly Sendinblue
  browserstack: { website: 'https://www.browserstack.com/', color: colors[2] },
  bytebase: {
    website: 'https://www.bytebase.com/',
    github: 'bytebase/bytebase',
    color: colors[3],
  },
  c: { website: 'https://en.wikipedia.org/wiki/C_(programming_language)', color: colors[4] },
  caddy: { website: 'https://caddyserver.com/', github: 'caddyserver/caddy', color: colors[5] },
  celery: { website: 'https://docs.celeryq.dev/', github: 'celery/celery', color: colors[6] },
  checkov: {
    website: 'https://www.checkov.io/',
    github: 'bridgecrewio/checkov',
    color: colors[7],
  },
  chef: { website: 'https://www.chef.io/', github: 'chef/chef', color: colors[7] },
  circleci: { website: 'https://circleci.com/', color: colors[9] },
  cirrusci: { website: 'https://cirrus-ci.org/', color: colors[0] },
  clerk: { website: 'https://clerk.com/', color: colors[1] },
  clickhouse: {
    website: 'https://clickhouse.com/',
    github: 'ClickHouse/ClickHouse',
    color: colors[2],
  },
  clicksend: { website: 'https://www.clicksend.com/', color: colors[3] },
  'cloudbees.codeship': {
    website: 'https://www.cloudbees.com/products/codeship',
    color: colors[4],
  },
  cloudbees: { website: 'https://www.cloudbees.com/', color: colors[5] },
  'cloudflare.pages': { website: 'https://pages.cloudflare.com/', color: colors[6] },
  'cloudflare.workers': { website: 'https://workers.cloudflare.com/', color: colors[7] },
  cloudflare: { website: 'https://www.cloudflare.com/', color: colors[7] },
  cockroachdb: {
    website: 'https://www.cockroachlabs.com/',
    github: 'cockroachdb/cockroach',
    color: colors[9],
  },
  codeclimate: { website: 'https://codeclimate.com/', color: colors[0] },
  codecov: { website: 'https://about.codecov.io/', color: colors[1] },
  codesandboxci: { website: 'https://codesandbox.io/ci', color: colors[2] },
  cohereai: { website: 'https://cohere.com/', color: colors[3] },
  commercetools: { website: 'https://commercetools.com/', color: colors[4] },
  consul: { website: 'https://www.consul.io/', github: 'hashicorp/consul', color: colors[5] },
  contenful: { website: 'https://www.contentful.com/', color: colors[6] },
  convexdb: { website: 'https://www.convex.dev/', github: 'get-convex/convex', color: colors[7] },
  couchbase: { website: 'https://www.couchbase.com/', color: colors[7] },
  coveralls: { website: 'https://coveralls.io/', color: colors[9] },
  cplusplus: { website: 'https://isocpp.org/', color: colors[0] },
  cratedb: { website: 'https://cratedb.com/', github: 'crate/crate', color: colors[1] },
  crowdin: { website: 'https://crowdin.com/', color: colors[2] },
  csharp: { website: 'https://dotnet.microsoft.com/en-us/languages/csharp', color: colors[3] },
  css: { website: 'https://www.w3.org/Style/CSS/', color: colors[4] },
  cypressci: {
    website: 'https://www.cypress.io/',
    github: 'cypress-io/cypress',
    color: colors[5],
  },
  d3js: { website: 'https://d3js.org/', github: 'd3/d3', color: colors[6] },
  dart: { website: 'https://dart.dev/', github: 'dart-lang/sdk', color: colors[7] },
  databricks: { website: 'https://www.databricks.com/', color: colors[7] },
  datadog: { website: 'https://www.datadoghq.com/', color: colors[9] },
  dataiku: { website: 'https://www.dataiku.com/', color: colors[0] },
  datastax: { website: 'https://www.datastax.com/', color: colors[1] },
  datocms: { website: 'https://www.datocms.com/', color: colors[2] },
  deepseek: { website: 'https://www.deepseek.com/', color: colors[3] },
  deferrun: { website: 'https://www.defer.run/', color: colors[4] },
  deno: { website: 'https://deno.land/', github: 'denoland/deno', color: colors[5] },
  denodeploy: { website: 'https://deno.com/deploy', color: colors[6] },
  dependabot: {
    website: 'https://github.com/dependabot',
    github: 'dependabot/dependabot-core',
    color: colors[7],
  },
  digitalocean: { website: 'https://www.digitalocean.com/', color: colors[7] },
  discord: { website: 'https://discord.com/', color: colors[9] },
  discourse: {
    website: 'https://www.discourse.org/',
    github: 'discourse/discourse',
    color: colors[0],
  },
  docker: { website: 'https://www.docker.com/', github: 'moby/moby', color: colors[1] },
  doctrinephp: {
    website: 'https://www.doctrine-project.org/',
    github: 'doctrine/orm',
    color: colors[2],
  },
  docusaurus: {
    website: 'https://docusaurus.io/',
    github: 'facebook/docusaurus',
    color: colors[3],
  },
  docusign: { website: 'https://www.docusign.com/', color: colors[4] },
  droneci: { website: 'https://www.drone.io/', github: 'drone/drone', color: colors[5] },
  dropbox: { website: 'https://www.dropbox.com/', color: colors[6] },
  drupal: { website: 'https://www.drupal.org/', github: 'drupal/drupal', color: colors[7] },
  duckdb: { website: 'https://duckdb.org/', github: 'duckdb/duckdb', color: colors[7] },
  dynatrace: { website: 'https://www.dynatrace.com/', color: colors[9] },
  elasticcloud: { website: 'https://www.elastic.co/cloud/', color: colors[0] },
  elasticsearch: {
    website: 'https://www.elastic.co/elasticsearch/',
    github: 'elastic/elasticsearch',
    color: colors[1],
  },
  elasticstack: { website: 'https://www.elastic.co/elastic-stack/', color: colors[2] },
  electron: {
    website: 'https://www.electronjs.org/',
    github: 'electron/electron',
    color: colors[3],
  },
  eleventy: { website: 'https://www.11ty.dev/', github: '11ty/eleventy', color: colors[4] },
  elixir: { website: 'https://elixir-lang.org/', github: 'elixir-lang/elixir', color: colors[5] },
  emberjs: { website: 'https://emberjs.com/', github: 'emberjs/ember.js', color: colors[6] },
  equinix: { website: 'https://www.equinix.com/', color: colors[7] },
  esbuild: { website: 'https://esbuild.github.io/', github: 'evanw/esbuild', color: colors[7] },
  eslint: { website: 'https://eslint.org/', github: 'eslint/eslint', color: colors[9] },
  expodev: { website: 'https://expo.dev/', color: colors[0] },
  expojs: { website: 'https://expo.dev/', github: 'expo/expo', color: colors[1] }, // Same as expodev
  express: { website: 'https://expressjs.com/', github: 'expressjs/express', color: colors[2] },
  fabric: { website: 'http://www.fabfile.org/', github: 'fabric/fabric', color: colors[3] }, // Python deployment tool
  facebook: { website: 'https://about.facebook.com/', color: colors[4] },
  fastify: { website: 'https://fastify.dev/', github: 'fastify/fastify', color: colors[5] },
  fastly: { website: 'https://www.fastly.com/', color: colors[6] },
  figma: { website: 'https://www.figma.com/', color: colors[7] },
  'firebase.firestore': {
    website: 'https://firebase.google.com/docs/firestore',
    color: colors[7],
  },
  firebase: { website: 'https://firebase.google.com/', color: colors[9] },
  flyio: { website: 'https://fly.io/', color: colors[0] },
  flyway: { website: 'https://flywaydb.org/', github: 'redgate-oss/flyway', color: colors[1] },
  gatsby: { website: 'https://www.gatsbyjs.com/', github: 'gatsbyjs/gatsby', color: colors[2] },
  'gcp.aiplatform': { website: 'https://cloud.google.com/vertex-ai', color: colors[3] }, // Renamed to Vertex AI
  'gcp.appengine': { website: 'https://cloud.google.com/appengine', color: colors[4] },
  'gcp.artifactregistry': {
    website: 'https://cloud.google.com/artifact-registry',
    color: colors[5],
  },
  'gcp.bigquery': { website: 'https://cloud.google.com/bigquery', color: colors[6] },
  'gcp.bigtable': { website: 'https://cloud.google.com/bigtable', color: colors[7] },
  'gcp.cloudbuild': { website: 'https://cloud.google.com/build', color: colors[7] },
  'gcp.cloudrun': { website: 'https://cloud.google.com/run', color: colors[9] },
  'gcp.containerregistry': {
    website: 'https://cloud.google.com/container-registry',
    color: colors[0],
  }, // Being replaced by Artifact Registry
  'gcp.dataflow': { website: 'https://cloud.google.com/dataflow', color: colors[1] },
  'gcp.dataproc': { website: 'https://cloud.google.com/dataproc', color: colors[2] },
  'gcp.datastore': { website: 'https://cloud.google.com/datastore', color: colors[3] }, // Now Firestore in Datastore mode
  'gcp.dialogflow': { website: 'https://cloud.google.com/dialogflow', color: colors[4] },
  'gcp.dns': { website: 'https://cloud.google.com/dns', color: colors[5] },
  'gcp.functions': { website: 'https://cloud.google.com/functions', color: colors[6] },
  'gcp.gce': { website: 'https://cloud.google.com/compute', color: colors[7] },
  'gcp.gcs': { website: 'https://cloud.google.com/storage', color: colors[7] },
  'gcp.gke': { website: 'https://cloud.google.com/kubernetes-engine', color: colors[9] },
  'gcp.kms': { website: 'https://cloud.google.com/kms', color: colors[0] },
  'gcp.language': { website: 'https://cloud.google.com/natural-language', color: colors[1] },
  'gcp.logging': { website: 'https://cloud.google.com/logging', color: colors[2] },
  'gcp.maps': { website: 'https://developers.google.com/maps', color: colors[3] },
  'gcp.memorystore': { website: 'https://cloud.google.com/memorystore', color: colors[4] },
  'gcp.pubsub': { website: 'https://cloud.google.com/pubsub', color: colors[5] },
  'gcp.secretmanager': { website: 'https://cloud.google.com/secret-manager', color: colors[6] },
  'gcp.spanner': { website: 'https://cloud.google.com/spanner', color: colors[7] },
  'gcp.speech': { website: 'https://cloud.google.com/speech-to-text', color: colors[7] },
  'gcp.sql': { website: 'https://cloud.google.com/sql', color: colors[9] },
  'gcp.tasks': { website: 'https://cloud.google.com/tasks', color: colors[0] },
  'gcp.translate': { website: 'https://cloud.google.com/translate', color: colors[1] },
  'gcp.vision': { website: 'https://cloud.google.com/vision', color: colors[2] },
  gcp: { website: 'https://cloud.google.com/', color: colors[3] },
  geminiai: { website: 'https://gemini.google.com/', color: colors[4] },
  ghost: { website: 'https://ghost.org/', github: 'TryGhost/Ghost', color: colors[5] },
  gitbook: { website: 'https://www.gitbook.com/', color: colors[6] },
  gitguardian: { website: 'https://www.gitguardian.com/', color: colors[7] },
  'github.actions': {
    website: 'https://github.com/features/actions',
    github: 'actions/runner',
    color: colors[7],
  },
  'github.pages': {
    website: 'https://pages.github.com/',
    github: 'github/pages-gem',
    color: colors[9],
  },
  github: { website: 'https://github.com/', github: 'github/roadmap', color: colors[0] }, // Using roadmap as a placeholder public repo
  'gitlab.ci': { website: 'https://docs.gitlab.com/ee/ci/', color: colors[1] },
  'github.codeql': { website: 'https://codeql.github.com/', color: colors[2] },
  gitlab: { website: 'https://about.gitlab.com/', github: 'gitlab-org/gitlab', color: colors[3] },
  goacmelego: {
    website: 'https://go-acme.github.io/lego/',
    github: 'go-acme/lego',
    color: colors[4],
  },
  golang: { website: 'https://go.dev/', github: 'golang/go', color: colors[5] },
  golangcilint: {
    website: 'https://golangci-lint.run/',
    github: 'golangci/golangci-lint',
    color: colors[6],
  },
  googleanalytics: { website: 'https://analytics.google.com/', color: colors[7] },
  gradio: { website: 'https://www.gradio.app/', github: 'gradio-app/gradio', color: colors[7] },
  grafana: { website: 'https://grafana.com/', github: 'grafana/grafana', color: colors[9] },
  gridsome: { website: 'https://gridsome.org/', github: 'gridsome/gridsome', color: colors[0] },
  groq: { website: 'https://groq.com/', color: colors[1] },
  haproxy: { website: 'https://www.haproxy.org/', github: 'haproxy/haproxy', color: colors[2] },
  hashicorp_vault: {
    website: 'https://www.vaultproject.io/',
    github: 'hashicorp/vault',
    color: colors[3],
  },
  healthchecksio: {
    website: 'https://healthchecks.io/',
    github: 'healthchecks/healthchecks',
    color: colors[4],
  },
  helm: { website: 'https://helm.sh/', github: 'helm/helm', color: colors[5] },
  heroku: { website: 'https://www.heroku.com/', color: colors[6] },
  hexojs: { website: 'https://hexo.io/', github: 'hexojs/hexo', color: colors[7] },
  hotjar: { website: 'https://www.hotjar.com/', color: colors[7] },
  html: { website: 'https://html.spec.whatwg.org/', color: colors[9] },
  httpd: { website: 'https://httpd.apache.org/', github: 'apache/httpd', color: colors[0] },
  hubspot: { website: 'https://www.hubspot.com/', color: colors[1] },
  huggingface: { website: 'https://huggingface.co/', color: colors[2] },
  hugo: { website: 'https://gohugo.io/', github: 'gohugoio/hugo', color: colors[3] },
  hyperdx: { website: 'https://hyperdx.io/', github: 'hyperdxio/hyperdx', color: colors[4] },
  hypertune: {
    website: 'https://hypertune.com/',
    github: 'hypertune/hypertune',
    color: colors[5],
  },
  ibmcloud: { website: 'https://www.ibm.com/cloud', color: colors[6] },
  iftt: { website: 'https://ifttt.com/', color: colors[7] },
  influxdb: {
    website: 'https://www.influxdata.com/',
    github: 'influxdata/influxdb',
    color: colors[7],
  },
  intercom: { website: 'https://www.intercom.com/', color: colors[9] },
  intuit: { website: 'https://www.intuit.com/', color: colors[0] },
  java: { website: 'https://www.java.com/', github: 'openjdk/jdk', color: colors[1] },
  javascript: {
    website: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
    color: colors[2],
  },
  jekyll: { website: 'https://jekyllrb.com/', github: 'jekyll/jekyll', color: colors[3] },
  jenkins: { website: 'https://www.jenkins.io/', github: 'jenkinsci/jenkins', color: colors[4] },
  jest: { website: 'https://jestjs.io/', github: 'jestjs/jest', color: colors[5] },
  joomla: { website: 'https://www.joomla.org/', github: 'joomla/joomla-cms', color: colors[6] },
  k6: { website: 'https://k6.io/', github: 'grafana/k6', color: colors[7] },
  kentico: { website: 'https://kentico.com/', color: colors[7] },
  kibana: {
    website: 'https://www.elastic.co/kibana/',
    github: 'elastic/kibana',
    color: colors[9],
  },
  klarna: { website: 'https://www.klarna.com/', color: colors[0] },
  klaviyo: { website: 'https://www.klaviyo.com/', color: colors[1] },
  koa: { website: 'https://koajs.com/', github: 'koajs/koa', color: colors[2] },
  koalaanalytics: { website: 'https://koala.io/', color: colors[3] }, // Assuming koala.io
  kong: { website: 'https://konghq.com/', github: 'Kong/kong', color: colors[4] },
  kotlin: { website: 'https://kotlinlang.org/', github: 'JetBrains/kotlin', color: colors[5] },
  koyeb: { website: 'https://www.koyeb.com/', color: colors[6] },
  kubernetes: {
    website: 'https://kubernetes.io/',
    github: 'kubernetes/kubernetes',
    color: colors[7],
  },
  lago: { website: 'https://www.getlago.com/', github: 'getlago/lago', color: colors[7] },
  laravel: { website: 'https://laravel.com/', github: 'laravel/laravel', color: colors[9] },
  launchdarkly: { website: 'https://launchdarkly.com/', color: colors[0] },
  lemonsqueezy: { website: 'https://www.lemonsqueezy.com/', color: colors[1] },
  libsql: { website: 'https://turso.tech/', github: 'libsql/libsql', color: colors[2] }, // Associated with Turso
  lighthouse: {
    website: 'https://developer.chrome.com/docs/lighthouse/',
    github: 'GoogleChrome/lighthouse',
    color: colors[3],
  },
  linear: { website: 'https://linear.app/', color: colors[4] },
  liquibase: {
    website: 'https://www.liquibase.org/',
    github: 'liquibase/liquibase',
    color: colors[5],
  },
  logrocket: { website: 'https://logrocket.com/', color: colors[6] },
  logsnag: { website: 'https://logsnag.com/', color: colors[7] },
  logstash: {
    website: 'https://www.elastic.co/logstash/',
    github: 'elastic/logstash',
    color: colors[7],
  },
  magento: {
    website: 'https://business.adobe.com/products/commerce/magento/magento-open-source.html',
    color: colors[9],
  }, // Now Adobe Commerce / Magento Open Source
  mailchimp: { website: 'https://mailchimp.com/', color: colors[0] },
  mailgun: { website: 'https://www.mailgun.com/', color: colors[1] },
  mailhog: {
    website: 'https://github.com/mailhog/MailHog',
    github: 'mailhog/MailHog',
    color: colors[2],
  },
  mailjet: { website: 'https://www.mailjet.com/', color: colors[3] },
  mariadb: { website: 'https://mariadb.org/', github: 'MariaDB/server', color: colors[4] },
  matomo: { website: 'https://matomo.org/', github: 'matomo-org/matomo', color: colors[5] },
  mattermost: {
    website: 'https://mattermost.com/',
    github: 'mattermost/mattermost',
    color: colors[6],
  },
  meilisearch: {
    website: 'https://www.meilisearch.com/',
    github: 'meilisearch/meilisearch',
    color: colors[7],
  },
  meilisearchcloud: { website: 'https://cloud.meilisearch.com/', color: colors[7] },
  memcached: {
    website: 'https://memcached.org/',
    github: 'memcached/memcached',
    color: colors[9],
  },
  meteorjs: { website: 'https://www.meteor.com/', github: 'meteor/meteor', color: colors[0] },
  milvusdb: { website: 'https://milvus.io/', github: 'milvus-io/milvus', color: colors[1] },
  mistralai: { website: 'https://mistral.ai/', color: colors[2] },
  mithriljs: {
    website: 'https://mithril.js.org/',
    github: 'MithrilJS/mithril.js',
    color: colors[3],
  },
  mixpanel: { website: 'https://mixpanel.com/', color: colors[4] },
  mongodb: { website: 'https://www.mongodb.com/', color: colors[5] },
  mongodbatlas: { website: 'https://www.mongodb.com/cloud/atlas', color: colors[6] },
  mongoexpress: {
    website: 'https://github.com/mongo-express/mongo-express',
    github: 'mongo-express/mongo-express',
    color: colors[7],
  },
  mysql: { website: 'https://www.mysql.com/', github: 'mysql/mysql-server', color: colors[7] },
  nango: { website: 'https://www.nango.dev/', github: 'NangoHQ/nango', color: colors[9] },
  nats: { website: 'https://nats.io/', github: 'nats-io/nats-server', color: colors[0] },
  neo4j: { website: 'https://neo4j.com/', github: 'neo4j/neo4j', color: colors[1] },
  neondb: { website: 'https://neon.tech/', github: 'neondatabase/neon', color: colors[2] },
  nestjs: { website: 'https://nestjs.com/', github: 'nestjs/nest', color: colors[3] },
  netlify: { website: 'https://www.netlify.com/', color: colors[4] },
  newrelic: { website: 'https://newrelic.com/', color: colors[5] },
  nextcloud: { website: 'https://nextcloud.com/', github: 'nextcloud/server', color: colors[6] },
  nextjs: { website: 'https://nextjs.org/', github: 'vercel/next.js', color: colors[7] },
  nginx: { website: 'https://nginx.org/', color: colors[7] }, // Official repo is Mercurial, GitHub is a mirror
  nodejs: { website: 'https://nodejs.org/', github: 'nodejs/node', color: colors[10] },
  notion: { website: 'https://www.notion.so/', color: colors[0] },
  novu: { website: 'https://novu.co/', github: 'novuhq/novu', color: colors[1] },
  nuxtjs: { website: 'https://nuxtjs.org/', github: 'nuxt/nuxt', color: colors[2] },
  nxcloud: { website: 'https://nx.app/', color: colors[3] },
  nxjs: { website: 'https://nx.dev/', github: 'nrwl/nx', color: colors[4] },
  oceanbase: {
    website: 'https://en.oceanbase.com/',
    github: 'oceanbase/oceanbase',
    color: colors[5],
  },
  okta: { website: 'https://www.okta.com/', color: colors[6] },
  onlineornot: { website: 'https://onlineornot.com/', color: colors[7] },
  openai: { website: 'https://openai.com/', color: colors[7] },
  optimizely: { website: 'https://www.optimizely.com/', color: colors[9] },
  oraclecloud: { website: 'https://www.oracle.com/cloud/', color: colors[0] },
  'ovh.database': {
    website: 'https://www.ovhcloud.com/en/public-cloud/databases/',
    color: colors[1],
  },
  'ovh.dedicated': { website: 'https://www.ovhcloud.com/en/bare-metal/', color: colors[2] },
  'ovh.kubernetes': {
    website: 'https://www.ovhcloud.com/en/public-cloud/kubernetes/',
    color: colors[3],
  },
  'ovh.storage': {
    website: 'https://www.ovhcloud.com/en/public-cloud/storage/',
    color: colors[4],
  },
  'ovh.vps': { website: 'https://www.ovhcloud.com/en/vps/', color: colors[5] },
  ovh: { website: 'https://www.ovhcloud.com/', color: colors[6] },
  pagerduty: { website: 'https://www.pagerduty.com/', color: colors[7] },
  papertrail: { website: 'https://www.papertrail.com/', color: colors[7] },
  payloadcms: {
    website: 'https://payloadcms.com/',
    github: 'payloadcms/payload',
    color: colors[9],
  },
  paypal: { website: 'https://www.paypal.com/', color: colors[0] },
  percona: { website: 'https://www.percona.com/', color: colors[1] },
  perplexityai: { website: 'https://www.perplexity.ai/', color: colors[2] },
  phaserjs: { website: 'https://phaser.io/', github: 'photonstorm/phaser', color: colors[3] },
  php: { website: 'https://www.php.net/', github: 'php/php-src', color: colors[4] },
  phppest: { website: 'https://pestphp.com/', github: 'pestphp/pest', color: colors[5] },
  phpstan: { website: 'https://phpstan.org/', github: 'phpstan/phpstan', color: colors[6] },
  phpunit: {
    website: 'https://phpunit.de/',
    github: 'sebastianbergmann/phpunit',
    color: colors[7],
  },
  pingdom: { website: 'https://www.pingdom.com/', color: colors[7] },
  pirschanalytics: { website: 'https://pirsch.io/', color: colors[9] },
  placekit: { website: 'https://placekit.io/', color: colors[0] },
  planetscale: { website: 'https://planetscale.com/', color: colors[1] },
  platformsh: { website: 'https://platform.sh/', color: colors[2] },
  plausible: { website: 'https://plausible.io/', github: 'plausible/analytics', color: colors[3] },
  playwright: {
    website: 'https://playwright.dev/',
    github: 'microsoft/playwright',
    color: colors[4],
  },
  pnpm: { website: 'https://pnpm.io/', github: 'pnpm/pnpm', color: colors[5] },
  postgresql: {
    website: 'https://www.postgresql.org/',
    github: 'postgres/postgres',
    color: colors[6],
  },
  postgrest: {
    website: 'https://postgrest.org/',
    github: 'PostgREST/postgrest',
    color: colors[7],
  },
  posthog: { website: 'https://posthog.com/', github: 'PostHog/posthog', color: colors[7] },
  postman: { website: 'https://www.postman.com/', color: colors[9] },
  postmark: { website: 'https://postmarkapp.com/', color: colors[0] },
  powershell: {
    website: 'https://learn.microsoft.com/en-us/powershell/',
    github: 'PowerShell/PowerShell',
    color: colors[1],
  },
  preactjs: { website: 'https://preactjs.com/', github: 'preactjs/preact', color: colors[2] },
  prestashop: {
    website: 'https://www.prestashop.com/',
    github: 'PrestaShop/PrestaShop',
    color: colors[3],
  },
  prettier: { website: 'https://prettier.io/', github: 'prettier/prettier', color: colors[4] },
  prisma: { website: 'https://www.prisma.io/', github: 'prisma/prisma', color: colors[5] },
  prismacloud: { website: 'https://www.paloaltonetworks.com/prisma/cloud', color: colors[6] },
  prometheus: {
    website: 'https://prometheus.io/',
    github: 'prometheus/prometheus',
    color: colors[7],
  },
  puppeteer: { website: 'https://pptr.dev/', github: 'puppeteer/puppeteer', color: colors[7] },
  python: {
    website: 'https://www.python.org/',
    github: 'python/cpython',
    iconURL: 'https://avatars.githubusercontent.com/u/1525981?s=200&v=4',
    color: colors[9],
  },
  pytorch: { website: 'https://pytorch.org/', github: 'pytorch/pytorch', color: colors[0] },
  qdrant: { website: 'https://qdrant.tech/', github: 'qdrant/qdrant', color: colors[1] },
  'qovery.cluster': { website: 'https://www.qovery.com/cluster', color: colors[2] },
  'qovery.database': { website: 'https://www.qovery.com/database', color: colors[3] },
  qovery: { website: 'https://www.qovery.com/', color: colors[4] },
  questdb: { website: 'https://questdb.io/', github: 'questdb/questdb', color: colors[5] },
  rabbitmq: {
    website: 'https://www.rabbitmq.com/',
    github: 'rabbitmq/rabbitmq-server',
    color: colors[6],
  },
  'railway.mongodb': { website: 'https://railway.app/template/mongodb', color: colors[7] },
  'railway.mysql': { website: 'https://railway.app/template/mysql', color: colors[7] },
  'railway.postgres': { website: 'https://railway.app/template/postgresql', color: colors[9] },
  'railway.redis': { website: 'https://railway.app/template/redis', color: colors[0] },
  railway: { website: 'https://railway.app/', color: colors[1] },
  react: { website: 'https://react.dev/', github: 'facebook/react', color: colors[2] },
  reactemail: { website: 'https://react.email/', github: 'resend/react-email', color: colors[3] },
  redis: { website: 'https://redis.io/', github: 'redis/redis', color: colors[4] },
  redwoodjs: { website: 'https://redwoodjs.com/', github: 'redwoodjs/redwood', color: colors[5] },
  refinedev: { website: 'https://refine.dev/', github: 'refinedev/refine', color: colors[6] },
  relativeci: { website: 'https://relative-ci.com/', color: colors[7] },
  remixrun: { website: 'https://remix.run/', github: 'remix-run/remix', color: colors[7] },
  render: { website: 'https://render.com/', color: colors[9] },
  renovate: {
    website: 'https://github.com/renovatebot/renovate',
    github: 'renovatebot/renovate',
    color: colors[0],
  },
  'replit.database': {
    website: 'https://docs.replit.com/hosting/databases/replit-database',
    color: colors[1],
  },
  'replit.postgres': {
    website: 'https://docs.replit.com/hosting/databases/postgresql-databases',
    color: colors[2],
  },
  replit: { website: 'https://replit.com/', color: colors[3] },
  resend: { website: 'https://resend.com/', color: colors[4] },
  rethinkdb: {
    website: 'https://rethinkdb.com/',
    github: 'rethinkdb/rethinkdb',
    color: colors[5],
  },
  rollbar: { website: 'https://rollbar.com/', color: colors[6] },
  rollup: { website: 'https://rollupjs.org/', github: 'rollup/rollup', color: colors[7] },
  ruby: { website: 'https://www.ruby-lang.org/', github: 'ruby/ruby', color: colors[7] },
  rust: { website: 'https://www.rust-lang.org/', github: 'rust-lang/rust', color: colors[9] },
  salesforce: { website: 'https://www.salesforce.com/', color: colors[0] },
  sanity: { website: 'https://www.sanity.io/', github: 'sanity-io/sanity', color: colors[1] },
  sap: { website: 'https://www.sap.com/', color: colors[2] },
  sas: { website: 'https://www.sas.com/', color: colors[3] },
  'scaleway.container': { website: 'https://www.scaleway.com/en/containers/', color: colors[4] },
  'scaleway.database': { website: 'https://www.scaleway.com/en/database/', color: colors[5] },
  'scaleway.documentdb': {
    website: 'https://www.scaleway.com/en/document-database/',
    color: colors[6],
  },
  'scaleway.elasticmetal': {
    website: 'https://www.scaleway.com/en/elastic-metal/',
    color: colors[7],
  },
  'scaleway.function': {
    website: 'https://www.scaleway.com/en/serverless-functions/',
    color: colors[7],
  },
  'scaleway.kubernetes': {
    website: 'https://www.scaleway.com/en/kubernetes-kapsule/',
    color: colors[9],
  },
  'scaleway.mq': {
    website: 'https://www.scaleway.com/en/managed-message-queues/',
    color: colors[0],
  },
  'scaleway.redis': { website: 'https://www.scaleway.com/en/redis-database/', color: colors[1] },
  'scaleway.secretmanager': {
    website: 'https://www.scaleway.com/en/secret-manager/',
    color: colors[2],
  },
  'scaleway.storage': { website: 'https://www.scaleway.com/en/object-storage/', color: colors[3] },
  scaleway: { website: 'https://www.scaleway.com/', color: colors[4] },
  scoutapm: { website: 'https://scoutapm.com/', color: colors[5] },
  scss: { website: 'https://sass-lang.com/', github: 'sass/sass', color: colors[6] }, // Sass is the parent technology
  selenium: {
    website: 'https://www.selenium.dev/',
    github: 'SeleniumHQ/selenium',
    color: colors[7],
  },
  sendgrid: { website: 'https://sendgrid.com/', color: colors[7] },
  sentry: { website: 'https://sentry.io/', github: 'getsentry/sentry', color: colors[9] },
  sequelize: {
    website: 'https://sequelize.org/',
    github: 'sequelize/sequelize',
    color: colors[0],
  },
  servicenow: { website: 'https://www.servicenow.com/', color: colors[1] },
  'shopify.hydrogen': { website: 'https://hydrogen.shopify.dev/', color: colors[2] },
  shopify: { website: 'https://www.shopify.com/', color: colors[3] },
  signoz: { website: 'https://signoz.io/', github: 'SigNoz/signoz', color: colors[4] },
  'sitecore.xmlcloud': { website: 'https://www.sitecore.com/products/xm-cloud', color: colors[5] },
  sitecore: { website: 'https://www.sitecore.com/', color: colors[6] },
  slack: { website: 'https://slack.com/', color: colors[7] },
  snowflake: { website: 'https://www.snowflake.com/', color: colors[7] },
  snyk: { website: 'https://snyk.io/', color: colors[9] },
  socketio: { website: 'https://socket.io/', github: 'socketio/socket.io', color: colors[0] },
  solidjs: { website: 'https://www.solidjs.com/', github: 'solidjs/solid', color: colors[1] },
  sonarcloud: { website: 'https://sonarcloud.io/', color: colors[2] },
  sonarlint: { website: 'https://www.sonarsource.com/products/sonarlint/', color: colors[3] },
  sonarqube: { website: 'https://www.sonarsource.com/products/sonarqube/', color: colors[4] },
  splitio: { website: 'https://www.split.io/', color: colors[5] },
  splunk: { website: 'https://www.splunk.com/', color: colors[6] },
  sqlite: { website: 'https://www.sqlite.org/', github: 'sqlite/sqlite', color: colors[7] }, // Mirror, main is Fossil
  sqreen: {
    website: 'https://www.datadoghq.com/product/application-security-monitoring/',
    color: colors[7],
  }, // Acquired by Datadog
  squarespace: { website: 'https://www.squarespace.com/', color: colors[9] },
  squareup: { website: 'https://squareup.com/', color: colors[0] },
  storybook: {
    website: 'https://storybook.js.org/',
    github: 'storybookjs/storybook',
    color: colors[1],
  },
  strapi: { website: 'https://strapi.io/', github: 'strapi/strapi', color: colors[2] },
  stripe: { website: 'https://stripe.com/', color: colors[3] },
  styleci: { website: 'https://styleci.io/', color: colors[4] },
  stylelint: { website: 'https://stylelint.io/', github: 'stylelint/stylelint', color: colors[5] },
  'supabase.auth': { website: 'https://supabase.com/docs/guides/auth', color: colors[6] },
  'supabase.functions': {
    website: 'https://supabase.com/docs/guides/functions',
    color: colors[7],
  },
  'supabase.postgres': { website: 'https://supabase.com/docs/guides/database', color: colors[7] },
  'supabase.realtime': { website: 'https://supabase.com/docs/guides/realtime', color: colors[9] },
  'supabase.storage': { website: 'https://supabase.com/docs/guides/storage', color: colors[0] },
  supabase: { website: 'https://supabase.com/', github: 'supabase/supabase', color: colors[1] },
  surrealdb: {
    website: 'https://surrealdb.com/',
    github: 'surrealdb/surrealdb',
    color: colors[2],
  },
  sveltejs: { website: 'https://svelte.dev/', github: 'sveltejs/svelte', color: colors[3] },
  swift: { website: 'https://www.swift.org/', github: 'apple/swift', color: colors[4] },
  symfony: { website: 'https://symfony.com/', github: 'symfony/symfony', color: colors[5] },
  tailscale: { website: 'https://tailscale.com/', color: colors[6] },
  tailwind: {
    website: 'https://tailwindcss.com/',
    github: 'tailwindlabs/tailwindcss',
    color: colors[7],
  },
  tanstackstart: {
    website: 'https://tanstack.com/start/latest',
    github: 'TanStack/start',
    color: colors[7],
  },
  tdengine: { website: 'https://tdengine.com/', github: 'taosdata/TDengine', color: colors[9] },
  teamcity: { website: 'https://www.jetbrains.com/teamcity/', color: colors[0] },
  teamspeak: { website: 'https://www.teamspeak.com/', color: colors[1] },
  telegraf: {
    website: 'https://www.influxdata.com/time-series-platform/telegraf/',
    github: 'influxdata/telegraf',
    color: colors[2],
  },
  telegram: { website: 'https://telegram.org/', color: colors[3] },
  tencentcloud: { website: 'https://www.tencentcloud.com/', color: colors[4] },
  tensorflow: {
    website: 'https://www.tensorflow.org/',
    github: 'tensorflow/tensorflow',
    color: colors[5],
  },
  terraform: {
    website: 'https://www.terraform.io/',
    github: 'hashicorp/terraform',
    color: colors[6],
  },
  terragrunt: {
    website: 'https://terragrunt.gruntwork.io/',
    github: 'gruntwork-io/terragrunt',
    color: colors[7],
  },
  tidb: {
    website: 'https://pingcap.com/products/tidb/',
    github: 'pingcap/tidb',
    color: colors[7],
  },
  timescaledb: {
    website: 'https://www.timescale.com/',
    github: 'timescale/timescaledb',
    color: colors[9],
  },
  tinybird: { website: 'https://www.tinybird.co/', color: colors[0] },
  traefik: { website: 'https://traefik.io/', github: 'traefik/traefik', color: colors[1] },
  travisci: { website: 'https://www.travis-ci.com/', color: colors[2] },
  trufflesecurity: { website: 'https://trufflesecurity.com/', color: colors[3] },
  turborepo: { website: 'https://turbo.build/repo', github: 'vercel/turbo', color: colors[4] },
  tursodb: { website: 'https://turso.tech/', github: 'tursodatabase/libsql', color: colors[5] }, // Same as libsql
  twigphp: { website: 'https://twig.symfony.com/', github: 'twigphp/Twig', color: colors[6] },
  twilio: { website: 'https://www.twilio.com/', color: colors[7] },
  twitter: { website: 'https://twitter.com/', color: colors[7] },
  typescript: {
    website: 'https://www.typescriptlang.org/',
    github: 'microsoft/TypeScript',
    color: colors[11],
  },
  typesense: {
    website: 'https://typesense.org/',
    github: 'typesense/typesense',
    color: colors[0],
  },
  typesensecloud: { website: 'https://cloud.typesense.org/', color: colors[1] },
  'upstash.kafka': { website: 'https://upstash.com/kafka', color: colors[2] },
  'upstash.qstash': { website: 'https://upstash.com/qstash', color: colors[3] },
  'upstash.redis': { website: 'https://upstash.com/redis', color: colors[4] },
  upstash: { website: 'https://upstash.com/', color: colors[5] },
  uptimekuma: {
    website: 'https://github.com/louislam/uptime-kuma',
    github: 'louislam/uptime-kuma',
    color: colors[6],
  },
  vale: { website: 'https://vale.sh/', github: 'errata-ai/vale', color: colors[7] },
  'vercel.ai': { website: 'https://vercel.com/ai', color: colors[7] },
  'vercel.analytics': { website: 'https://vercel.com/analytics', color: colors[9] },
  'vercel.blob': { website: 'https://vercel.com/blob', color: colors[0] },
  'vercel.edge': { website: 'https://vercel.com/edge', color: colors[1] },
  'vercel.kv': { website: 'https://vercel.com/kv', color: colors[2] },
  'vercel.postgres': { website: 'https://vercel.com/postgres', color: colors[3] },
  vercel: { website: 'https://vercel.com/', color: colors[4] },
  veriff: { website: 'https://www.veriff.com/', color: colors[5] },
  vialink: { website: 'https://vialink.fr/', color: colors[6] },
  victoriametrics: {
    website: 'https://victoriametrics.com/',
    github: 'VictoriaMetrics/VictoriaMetrics',
    color: colors[7],
  },
  vite: { website: 'https://vitejs.dev/', github: 'vitejs/vite', color: colors[7] },
  vue: { website: 'https://vuejs.org/', github: 'vuejs/vue', color: colors[9] },
  wasp: { website: 'https://wasp-lang.dev/', github: 'wasp-lang/wasp', color: colors[0] },
  webflow: { website: 'https://webflow.com/', color: colors[1] },
  webpack: { website: 'https://webpack.js.org/', github: 'webpack/webpack', color: colors[2] },
  wiz: { website: 'https://www.wiz.io/', color: colors[3] },
  woocommerce: {
    website: 'https://woocommerce.com/',
    github: 'woocommerce/woocommerce',
    color: colors[4],
  },
  wordpress: {
    website: 'https://wordpress.org/',
    github: 'WordPress/wordpress-develop',
    color: colors[5],
  }, // Dev repo
  workos: { website: 'https://workos.com/', color: colors[6] },
  xai: { website: 'https://x.ai/', color: colors[7] },
  yarn: { website: 'https://yarnpkg.com/', github: 'yarnpkg/berry', color: colors[7] },
  yii2: { website: 'https://www.yiiframework.com/', github: 'yiisoft/yii2', color: colors[9] },
  yousign: { website: 'https://yousign.com/', color: colors[0] },
  zapier: { website: 'https://zapier.com/', color: colors[1] },
  zendesk: { website: 'https://www.zendesk.com/', color: colors[2] },
  zig: { website: 'https://ziglang.org/', github: 'ziglang/zig', color: colors[3] },
  zipkin: { website: 'https://zipkin.io/', github: 'openzipkin/zipkin', color: colors[4] },
  zookeeper: {
    website: 'https://zookeeper.apache.org/',
    github: 'apache/zookeeper',
    color: colors[5],
  },
  zoom: { website: 'https://zoom.us/', color: colors[6] },
  zuora: { website: 'https://www.zuora.com/', color: colors[7] },

  deepsource: { website: 'https://deepsource.com', color: colors[7] },
  depotdev: { website: 'https://depot.dev', color: colors[9] },
  infisical: { website: 'https://infisical.com/', color: colors[0] },
  mintlify: { website: 'https://mintlify.com/', color: colors[1] },
  vitest: { website: 'https://vitest.dev/', color: colors[2] },
  glsl: { website: 'https://www.khronos.org/opengl/wiki/Main_Page', color: colors[3] },
  radixui: { website: 'https://www.radix-ui.com/', color: colors[4] },
  tiptap: { website: 'https://tiptap.dev/', color: colors[5] },

  akamai: { website: 'https://www.akamai.com/', color: colors[6] },
  betterauth: { website: 'https://www.better-auth.com/', color: colors[7] },
  browerbase: { website: 'https://www.browserbase.com/', color: colors[7] },
  chargebee: { website: 'https://www.chargebee.com/', color: colors[9] },
  firecrawl: { website: 'https://firecrawl.dev/', color: colors[0] },
  hetzner: { website: 'https://www.hetzner.com/', color: colors[1] },
  hostinger: { website: 'https://www.hostinger.com/', color: colors[2] },
  inngest: { website: 'https://www.inngest.com/', color: colors[3] },
  logtoio: { website: 'https://logto.io/', color: colors[4] },
  metabase: { website: 'https://www.metabase.com/', color: colors[5] },
  n8n: { website: 'https://n8n.io/', color: colors[6] },
  paddle: { website: 'https://www.paddle.com/', color: colors[7] },
  pinecone: { website: 'https://www.pinecone.io/', color: colors[7] },
  pulumi: { website: 'https://www.pulumi.com/', color: colors[9] },
  twentycrm: { website: 'https://twenty.com/', color: colors[0] },
};

const extendedListTech = listTech.map((tech) => {
  const extended = extendedInfo[tech.key]!;

  return {
    ...tech,
    ...extended,
  };
});

export { extendedListTech };
