/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PrivateImport } from './routes/private'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as LicensesIndexImport } from './routes/licenses/index'
import { Route as TechTechKeyImport } from './routes/tech/$techKey'
import { Route as LicensesLicenseImport } from './routes/licenses/$license'
import { Route as CategoryCategoryImport } from './routes/category/$category'
import { Route as OrgNameImport } from './routes/$org/$name'

// Create/Update Routes

const PrivateRoute = PrivateImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LicensesIndexRoute = LicensesIndexImport.update({
  id: '/licenses/',
  path: '/licenses/',
  getParentRoute: () => rootRoute,
} as any)

const TechTechKeyRoute = TechTechKeyImport.update({
  id: '/tech/$techKey',
  path: '/tech/$techKey',
  getParentRoute: () => rootRoute,
} as any)

const LicensesLicenseRoute = LicensesLicenseImport.update({
  id: '/licenses/$license',
  path: '/licenses/$license',
  getParentRoute: () => rootRoute,
} as any)

const CategoryCategoryRoute = CategoryCategoryImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRoute,
} as any)

const OrgNameRoute = OrgNameImport.update({
  id: '/$org/$name',
  path: '/$org/$name',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/private': {
      id: '/private'
      path: '/private'
      fullPath: '/private'
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/$org/$name': {
      id: '/$org/$name'
      path: '/$org/$name'
      fullPath: '/$org/$name'
      preLoaderRoute: typeof OrgNameImport
      parentRoute: typeof rootRoute
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryImport
      parentRoute: typeof rootRoute
    }
    '/licenses/$license': {
      id: '/licenses/$license'
      path: '/licenses/$license'
      fullPath: '/licenses/$license'
      preLoaderRoute: typeof LicensesLicenseImport
      parentRoute: typeof rootRoute
    }
    '/tech/$techKey': {
      id: '/tech/$techKey'
      path: '/tech/$techKey'
      fullPath: '/tech/$techKey'
      preLoaderRoute: typeof TechTechKeyImport
      parentRoute: typeof rootRoute
    }
    '/licenses/': {
      id: '/licenses/'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/private': typeof PrivateRoute
  '/$org/$name': typeof OrgNameRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/licenses/$license': typeof LicensesLicenseRoute
  '/tech/$techKey': typeof TechTechKeyRoute
  '/licenses': typeof LicensesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/private': typeof PrivateRoute
  '/$org/$name': typeof OrgNameRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/licenses/$license': typeof LicensesLicenseRoute
  '/tech/$techKey': typeof TechTechKeyRoute
  '/licenses': typeof LicensesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/private': typeof PrivateRoute
  '/$org/$name': typeof OrgNameRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/licenses/$license': typeof LicensesLicenseRoute
  '/tech/$techKey': typeof TechTechKeyRoute
  '/licenses/': typeof LicensesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/private'
    | '/$org/$name'
    | '/category/$category'
    | '/licenses/$license'
    | '/tech/$techKey'
    | '/licenses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/private'
    | '/$org/$name'
    | '/category/$category'
    | '/licenses/$license'
    | '/tech/$techKey'
    | '/licenses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/private'
    | '/$org/$name'
    | '/category/$category'
    | '/licenses/$license'
    | '/tech/$techKey'
    | '/licenses/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivateRoute: typeof PrivateRoute
  OrgNameRoute: typeof OrgNameRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  LicensesLicenseRoute: typeof LicensesLicenseRoute
  TechTechKeyRoute: typeof TechTechKeyRoute
  LicensesIndexRoute: typeof LicensesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivateRoute: PrivateRoute,
  OrgNameRoute: OrgNameRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  LicensesLicenseRoute: LicensesLicenseRoute,
  TechTechKeyRoute: TechTechKeyRoute,
  LicensesIndexRoute: LicensesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/private",
        "/$org/$name",
        "/category/$category",
        "/licenses/$license",
        "/tech/$techKey",
        "/licenses/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/private": {
      "filePath": "private.tsx"
    },
    "/$org/$name": {
      "filePath": "$org/$name.tsx"
    },
    "/category/$category": {
      "filePath": "category/$category.tsx"
    },
    "/licenses/$license": {
      "filePath": "licenses/$license.tsx"
    },
    "/tech/$techKey": {
      "filePath": "tech/$techKey.tsx"
    },
    "/licenses/": {
      "filePath": "licenses/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
